name: echoeyes # App name shown in project files
description: Object Detection and Recognition Application for Visually Impaired.

publish_to: 'none' # Prevent from publishing the app to pub.dev

# Command reminder to build  a release APK
# flutter build apk --release

version: 1.0.0+1 # App version (1.0.0 is an app version, +1 is a build number)

# Flutter and Dart SDK requirements
environment:
  sdk: ^3.9.2

# External packeages used by the app
dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.1               # Access device aamera
  flutter_vision: ^2.0.0        # Computer Vision for run YOLO model 
  flutter_tts: ^4.2.3           # Convert Text-to-Speech 
  permission_handler: ^12.0.0+1 # Ask and handle app permissions
  shared_preferences: ^2.2.3    # Store small local data
  flutter_spinkit: ^5.2.2       # Provide 'loading' animations
  android_intent_plus: ^6.0.0   # Open Android system settings or intents


  # Provide iOS style icons
  cupertino_icons: ^1.0.8

# Packages used only during development
dev_dependencies:
  flutter_test:
    sdk: flutter # Unit and widget testing

  flutter_lints: ^6.0.0           # Code quality rules
  flutter_launcher_icons: ^0.14.4 # Generate app launcher icons

# launcher icon configurations (image, path,..)
# Command to run the app launcher icons ==> flutter pub run flutter_launcher_icons
flutter_icons:
  android: true                                           # Apply icons for Android: true
  image_path: "assets/icons/echo_icon.png"                # Launcher icon image path
  adaptive_icon_background: "#000000"                     # Background color
  adaptive_icon_foreground: "assets/icons/echo_icon.png"  # Foreground image path




flutter:


  # Enabe Material Design (Android) widgets
  uses-material-design: true

  # Assets included in this app
  assets:
    - assets/labels/label.txt           # Object class labels
    - assets/yolov8n.tflite             # Model (original)
    - assets/best_float32.tflite        # Converted version of TensorFlow Lite best-trained model
    - assets/images/echoeyes2_logo.png  # App logo image
    - assets/icons/echoeyes2_logo.png   # Icon variant
    - assets/icons/echo_icon.png        # Icon (original)


  # Custom fonts used in this app
  fonts:
      - family: Poppins # Main font used in all screens
        fonts:
            - asset: assets/fonts/Poppins-Regular.ttf
            - asset: assets/fonts/Poppins-Bold.ttf
              weight: 700
            - asset: assets/fonts/Poppins-SemiBold.ttf
              weight: 600
            - asset: assets/fonts/Poppins-Medium.ttf
              weight: 500
            - asset: assets/fonts/Poppins-ExtraBold.ttf
              weight: 900
      - family: Quattrocento # Decorative font (splash_screen)
        fonts:
            - asset: assets/fonts/Quattrocento-Regular.ttf
            - asset: assets/fonts/Quattrocento-Bold.ttf
              weight: 700
      - family: Marcellus   # Decorative font (splash_screen)
        fonts:
            - asset: assets/fonts/Marcellus-Regular.ttf
            